name: 04 - Using Actions
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: 04-using-actions/react-app
    steps:
      - name: Parsing Folder Before Checkout
        run: ls

      # 0. Checkout the code from the repository
      # workflow가 repository내에 정의되었더라도, default로 repository code는 workflow에서 활용할 수 없음..
      # 따라서, checkout action을 사용하여 repository code를 current working directory로 가져와야 함
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Parsing Folder After Checkout
        run: ls

      # 1. Install dependencies of our react application
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          # 버전 20 중 Latest version설치하는 syntax임

      - name: Install Dependencies
       
        run: |
          npm ci
        
        # run의 명령어를 정의한 working-directory에서 실행되도록 함. (물론 그냥 cd로 이동해서 명령어 실행해도 같은 효과임)
        # default로 정의가능(위 코드 참고)
        working-directory: 04-using-actions/react-app
        
      - name: Run Unit Test
        working-directory: 04-using-actions/react-app
        run: |
          npm run test


      # 2. Execute automated tests

        
