name: 06 - Contexts
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}
on:
  # push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: true
        description: "Enable debug mode"

env:
  MY_WORKFLOW_VAR: 'workflow'
  MY_OVERWRITTEN_VAR: 'workflow'

jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
      MY_JOB_VAR: 'job'
      MY_OVERWRITTEN_VAR: 'job'
    steps:
      - name: Display Information
        run: |
          echo "Event name: ${{github.event_name}}"
          echo "Ref(트리거된 브랜치 또는 태그): ${{github.ref}}"
          echo "SHA(커밋의 해시): ${{github.sha}}"
          echo "Repository(워크플로우가 실행된 리포지토리): ${{github.repository}}"
          echo "Actor(워크플로우를 트리거한 사용자): ${{github.actor}}"
          echo "Workflow(워크플로우의 이름): ${{github.workflow}}"
          echo "Run ID(워크플로우 실행의 고유 식별자): ${{github.run_id}}"
          echo "Run number(워크플로우 실행의 고유 번호. 이 Workflow를 몇 번 실행했는지 횟수): ${{github.run_number}}"
      
      - name: Retrieve Variables
        run: |
          echo "MY_VAR(repository의 variable로 내가 설정한 커스텀 변수): ${{vars.MY_VAR}}"
      
      - name: Pring Env Variables
        env:
          MY_OVERWRITTEN_VAR: 'step'
        run: |
          echo "workflow env: ${{ env.MY_WORKFLOW_VAR }}"
          echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
  
  echo-data-2:
    runs-on: ubuntu-latest
    steps:
      - name: Pring Env Variables
        run: |
          echo "workflow env: $MY_WORKFLOW_VAR"
          echo "Overwritten env: $MY_OVERWRITTEN_VAR"

      
          