name: 10 - Controlling the Execution Flow
on:
  workflow_dispatch:
    inputs:
      pass-unit-tests:
        type: boolean
        default: false
        description: "Whether the unit tests passed"

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Lint and build
        run: |
          echo "Linting and building project"
      

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Unit test
        run: |
          echo "Running tests..."
      - name: Failing tests
        if: ${{inputs.pass-unit-tests == false}}
        run: |
          exit 1
  
  deploy-nonprod:
    runs-on: ubuntu-latest
    needs: [lint-build, unit-test]
    steps:
      - name: Deploying to nonprod
        run: |
          echo "Deploying to nonprod"
  
  e2e-tests:
    runs-on: ubuntu-latest
    needs: deploy-nonprod
    steps:
      - name: Running E2E tests
        run: echo "Running E2E tests"
      
      

  