name: My NPM workflow
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event_name == 'push' }}
        run: |
          echo "Triggered by a push event"
          echo "Running on ${{ github.ref_name }}"